{% set name = "goodtables" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf86a5e2e06520b353232d2edcea0fb103bf06090f1ccc28d0586c2e3decaa49

build:
  number: 0
  entry_points:
    - goodtables = goodtables.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9
    - click >=6.6
    - click-default-group
    - requests >=2.10
    - simpleeval >=0.9
    - statistics >=1.0  # [py2k]
    - tabulator >=1.20
    - tableschema >=1.0.3
    - datapackage >=1.2

test:
  imports:
    - goodtables
  commands:
    - goodtables --help

about:
  home: http://github.com/frictionlessdata/goodtables-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Goodtables is a framework to validate tabular data

extra:
  recipe-maintainers:
    - roll
