{% set name = "goodtables" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67c51ac98967684763adb6406f92a683571d144b3a80095b0351a65f49848027

build:
  number: 1
  noarch: python
  entry_points:
    - goodtables = goodtables.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=6.6
    - click-default-group
    - datapackage >=1.10
    - python >=3.6
    - requests >=2.10
    - simpleeval >=0.9
    - six >=1.9
    - statistics >=1.0
    - tableschema >=1.16.4
    - tabulator >=1.40

test:
  imports:
    - goodtables
    - goodtables.checks
  commands:
    - pip check
    - goodtables --help
  requires:
    - pip

about:
  home: http://github.com/frictionlessdata/goodtables-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Goodtables is a framework to validate tabular data

extra:
  recipe-maintainers:
    - roll
